### ISSUE TITLE
Figure of top authors is broken

### ISSUE THREAD

**Issue by konrad** [konrad/my_awesome_repository#2]
The list figure that should display the top 5 authors cannot be generated anymore.

**Comment by konrad** [comment]
That should be done by @MrsMaulwurf

**Comment by MrsMaulwurf** [comment]
Schaff ich gerade nicht

**Comment by konrad** [comment]
Thanks! Could @crltfrnk help here?

**Comment by konrad** [comment]
Many thank for the contribution.
